apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Deployment template for an Angular app served by a nginx webserver
    tags: angular, caddy
  name: ${NAME}${SUFFIX}
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${NAME}-allow-ingress
      labels:
        name: ${NAME}-allow-ingress
        app: ${APP_NAME}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      description: |
        Allow traffic from routes into the ${ROLE} container(s).
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      podSelector:
        matchLabels:
          role: ${ROLE}
          app: ${APP_NAME}
          env: ${TAG_NAME}
      policyTypes:
        - Ingress
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP_NAME}${SUFFIX}
        name: ${NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
      name: ${NAME}${SUFFIX}
    spec:
      replicas: 1
      selector:
        name: ${NAME}${SUFFIX}
        deploymentconfig: ${NAME}${SUFFIX}
      strategy:
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}${SUFFIX}
            name: ${NAME}${SUFFIX}
            app-group: ${APP_GROUP}
            role: ${ROLE}
            env: ${TAG_NAME}
            deploymentconfig: ${NAME}${SUFFIX}
        spec:
          volumes:
            - name: ${NAME}${SUFFIX}-nginx-config-volume
              configMap:
                name: ${APP_CONFIG_MAP_NAME}${SUFFIX}
                items:
                  - key: ${CADDY_CONFIG_FILE_NAME}
                    path: ${CADDY_CONFIG_FILE_NAME}
            - name: ${NAME}${SUFFIX}-app-config-volume
              configMap:
                name: ${APP_CONFIG_MAP_NAME}${SUFFIX}
                items:
                  - key: ${APP_CONFIG_FILE_NAME}
                    path: ${APP_CONFIG_FILE_NAME}
          containers:
            - image: ${NAME}${SUFFIX}
              imagePullPolicy: Always
              name: ${NAME}${SUFFIX}
              ports:
                - containerPort: 8080
                  protocol: TCP
              env: []
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              volumeMounts:
                - name: ${NAME}${SUFFIX}-nginx-config-volume
                  mountPath: ${CADDY_CONFIG_MOUNT_PATH}${CADDY_CONFIG_FILE_NAME}
                  subPath: ${CADDY_CONFIG_FILE_NAME}
                - name: ${NAME}${SUFFIX}-app-config-volume
                  mountPath: ${APP_CONFIG_MOUNT_PATH}${APP_CONFIG_FILE_NAME}
                  subPath: ${APP_CONFIG_FILE_NAME}
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                timeoutSeconds: 60
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                timeoutSeconds: 60
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}${SUFFIX}
            from:
              kind: ImageStreamTag
              namespace: ${IMAGE_NAMESPACE}
              name: ${SOURCE_IMAGE_NAME}:${TAG_NAME}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP_NAME}${SUFFIX}
        name: ${NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
      name: ${NAME}${SUFFIX}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        name: ${NAME}${SUFFIX}
        deploymentconfig: ${NAME}${SUFFIX}
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APP_NAME}${SUFFIX}
        name: ${NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
        certbot-managed: ${CERTBOT_MANAGED_ROUTE}
      name: ${NAME}${SUFFIX}
    spec:
      host: ${APPLICATION_DOMAIN}
      port:
        targetPort: 8080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}${SUFFIX}
        weight: 100
  # - kind: NetworkSecurityPolicy
  #   apiVersion: security.devops.gov.bc.ca/v1alpha1
  #   metadata:
  #     name: custom-${APP_NAME}-${NAME}${SUFFIX}-policy
  #     labels:
  #       name: custom-${APP_NAME}-${NAME}${SUFFIX}-policy
  #       app: ${APP_NAME}${SUFFIX}
  #       app-group: ${APP_GROUP}
  #       role: ${ROLE}
  #       env: ${TAG_NAME}
  #   spec:
  #     description: Allow the client to talk to the server.
  #     source:
  #       - - role=${ROLE}
  #         - app=${APP_NAME}${SUFFIX}
  #         - env=${TAG_NAME}
  #         - $namespace=${NAMESPACE_NAME}-${TAG_NAME}
  #     destination:
  #       - - role=server
  #         - app=${APP_NAME}${SUFFIX}
  #         - env=${TAG_NAME}
  #         - $namespace=${NAMESPACE_NAME}-${TAG_NAME}
parameters:
  - description: The name assigned to all of the openshift objects defined in this
      template. It is also the name of runtime image you want.
    displayName: Name
    name: NAME
    required: true
    value: dsc-chat-client
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: dsc-chat
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: dsc-chat
  - name: SUFFIX
    displayName: Suffix
    description: A suffix applied to all of the objects in this template.
    required: false
    value: ''
  - name: ROLE
    displayName: Role
    description: The role of this service within the application - used for Network
      Policies
    required: true
    value: client
  - name: CERTBOT_MANAGED_ROUTE
    displayName: Certbot Managed Route
    description: Flag indicating whether the routes certificates are managed by CertBot.
    required: true
    value: 'false'
  - description: The namespace where to get the above image name
    displayName: Image Namespace
    name: IMAGE_NAMESPACE
    required: true
    value: a99fd4-tools
  - name: NAMESPACE_NAME
    displayName: Namespace Name
    description: The name of the namespace being deployed to..
    required: true
    value: a99fd4
  - name: CADDY_CONFIG_MOUNT_PATH
    displayName: Caddy Config Mount Path
    description: The path to use to mount the configuration file(s).
    required: true
    value: /etc/caddy/
  - name: CADDY_CONFIG_FILE_NAME
    displayName: Caddy Config File Name
    description: The name of the Caddy configuration file.
    required: true
    value: Caddyfile
  - name: APP_CONFIG_MAP_NAME
    displayName: Application Config Map Name
    description: The name of the configuration map holding the data to configure the
      application.
    required: true
    value: dsc-chat-client-config
  - name: APP_CONFIG_MOUNT_PATH
    displayName: Application Config Mount Path
    description: The path to use to mount the configuration file(s).
    required: true
    value: /usr/share/nginx/html/assets/
  - name: APP_CONFIG_FILE_NAME
    displayName: Application Config File Name
    description: The name of the application configuration file.
    required: true
    value: config.json
  - description: The exposed hostname that will route to the service, e.g., myappname.apps.silver.devops.gov.bc.ca,
      if left blank a value will be defaulted.
    displayName: Application Hostname
    name: APPLICATION_DOMAIN
    value: ''
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the image to use for this resource.
    required: true
    value: dsc-chat-client
  - description: The TAG name for this environment, e.g., dev, test, prod
    displayName: Env TAG name
    name: TAG_NAME
    value: latest
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 10m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 250m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 100Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 256Mi
