def PIPELINE_NAME = "deployment/test"

node {
  def config = load "../workspace@script/jenkins/${PIPELINE_NAME}/config.groovy"

  config.APPS.each { appName ->
    stage("Deploying ${appName} to ${config.DESTINATION_TAG}") {
      script {
        openshift.withCluster() {
          openshift.withProject() {
            echo "Tagging ${appName}:${config.SOURCE_TAG} for deployment to ${config.DESTINATION_TAG} ..."
            openshift.tag("${appName}:${config.SOURCE_TAG}", "${appName}:${config.DESTINATION_TAG}")
          }
        }
      }
    }
  }
}